### PR TITLE
Setup automation with pre-commit-mirror-maker

### PR DESCRIPTION
**Pull request by fsouza**
We're gonna stick to the patterns in pre-commit-mirror-maker, which means:

- use `setup.py` instead of `pyproject.toml` to declare the dummy package
- remove `.pre-commit-config.yaml`, as that file isn't necessary here

### CODE REVIEW

**Comment by fsouza** [comment]
@charliermarsh I was able to test this locally, but in order to get this running, we'll need to:

1. merge this PR
2. delete the existing tags
3. manually trigger the workflow (or wait until it runs automatically on schedule)

I can push the commits with the versions here, but that won't include the tags.

**Comment by charliermarsh** [comment]
Awesome! Will review in the AM. Will this retroactively create tags for all past ruff versions? Or only future releases?

**Comment by fsouza** [comment]
> Awesome! Will review in the AM. Will this retroactively create tags for all past ruff versions? Or only future releases?

It does it retroactively too, with one commit and one tag for each. Here's the output from running it locally:

<details>
<summary>
pre-commit-mirror --language python --package-name ruff --entry ruff --types python --description "Run ruff to lint 
</summary>
<pre>
％ pre-commit-mirror --language python --package-name ruff --entry ruff --types python --description "Run ruff to lint Python files." --args='--fix' .
[automatic c1b93e0] Mirror: 0.0.13
 3 files changed, 21 insertions(+), 7 deletions(-)
 create mode 100644 .version
 create mode 100644 setup.py
[automatic ff29202] Mirror: 0.0.14
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 807ff2b] Mirror: 0.0.15
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 8950f85] Mirror: 0.0.16
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 7bcbc06] Mirror: 0.0.17
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 5321cc4] Mirror: 0.0.18
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 0f031dc] Mirror: 0.0.19
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 28ad5c6] Mirror: 0.0.20
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 97ec025] Mirror: 0.0.21
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic a2b2298] Mirror: 0.0.22
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 0130159] Mirror: 0.0.23
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 255ed62] Mirror: 0.0.24
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 390eacf] Mirror: 0.0.25
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic d090bed] Mirror: 0.0.28
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 43483eb] Mirror: 0.0.29
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 6055e0c] Mirror: 0.0.30
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic e5a5dd3] Mirror: 0.0.31
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic d85eae3] Mirror: 0.0.32
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 9bee895] Mirror: 0.0.33
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 77d37c1] Mirror: 0.0.34
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic d8b7d6f] Mirror: 0.0.35
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 3029016] Mirror: 0.0.36
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic ae828ad] Mirror: 0.0.37
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic af03f87] Mirror: 0.0.39
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 7afb91f] Mirror: 0.0.40
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic b72ce1f] Mirror: 0.0.42
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 0b6f7a1] Mirror: 0.0.43
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 5ace987] Mirror: 0.0.44
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 3c52d65] Mirror: 0.0.45
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 2514d93] Mirror: 0.0.46
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic f5a9492] Mirror: 0.0.47
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic d0b6d6a] Mirror: 0.0.48
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 2d70e0c] Mirror: 0.0.49
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 4dbd7fd] Mirror: 0.0.50
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic aa31ab3] Mirror: 0.0.51
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic c78e5a7] Mirror: 0.0.52
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic aa1f45c] Mirror: 0.0.53
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic aaf1833] Mirror: 0.0.54
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 6be1dbf] Mirror: 0.0.55
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic cc01b7c] Mirror: 0.0.57
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 435b228] Mirror: 0.0.58
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 0eb1b65] Mirror: 0.0.59
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 7f8fa0d] Mirror: 0.0.60
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 4e61eef] Mirror: 0.0.61
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 6d361c9] Mirror: 0.0.62
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 8ae64b6] Mirror: 0.0.63
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 4913c9f] Mirror: 0.0.64
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 38ebc46] Mirror: 0.0.65
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 8c48278] Mirror: 0.0.66
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 9337378] Mirror: 0.0.67
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 5f8be0b] Mirror: 0.0.68
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 827a4b0] Mirror: 0.0.69
 2 files changed, 2 insertions(+), 2 deletions(-)
％ cat .pre-commit-hooks.yaml
-   id: ruff
    name: ruff
    description: 'Run ruff to lint Python files.'
    entry: ruff
    language: python
    'types': [python]
    args: ["--fix"]
    require_serial: false
    additional_dependencies: []
    minimum_pre_commit_version: '0'
</pre>
</details>

It also write a local file called `.version` with the latest version, so if you want to have it only create the versions after 0.0.65, we could create a file named `.version` and write `0.0.65` to it, in that case the script would only create the tags after that:

```
％ echo 0.0.65>.version
％ pre-commit-mirror --language python --package-name ruff --entry ruff --types python --description "Run ruff to lint Python files." --args='--fix' .
[automatic 8c3e1f9] Mirror: 0.0.66
 3 files changed, 21 insertions(+), 7 deletions(-)
 create mode 100644 .version
 create mode 100644 setup.py
[automatic 7253cdf] Mirror: 0.0.67
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic 4131e48] Mirror: 0.0.68
 2 files changed, 2 insertions(+), 2 deletions(-)
[automatic c096fd3] Mirror: 0.0.69
 2 files changed, 2 insertions(+), 2 deletions(-)
％ git tag
v0.0.66
v0.0.67
v0.0.68
v0.0.69
```

If you prefer that, I can include that `.version` file in this PR.

**Comment by charliermarsh** [comment]
Okay cool -- looks great! I'll follow the steps you outlined above.

**Comment by charliermarsh** [comment]
Worked perfectly!

One issue is that we used `--entry ruff` when it should be `--entry lint` I think?

**Comment by fsouza** [comment]
> One issue is that we used `--entry ruff` when it should be `--entry lint` I think?

Hmm, I just tested and it seems to work? Is `lint` a sub-command or something like that? `entry` is the executable that will be executed, so if we want to run something like `ruff lint`, we'd set entry to `ruff` and pass `lint` as an argument.

**Comment by charliermarsh** [comment]
Yeah it totally works! It just may not be backwards compatible?

E.g., I had this in an existing repo:

```
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.69
    hooks:
      - id: lint
```

Which now yields:

```
[ERROR] `lint` is not present in repository https://github.com/charliermarsh/ruff-pre-commit.  Typo? Perhaps it is introduced in a newer version?  Often `pre-commit autoupdate` fixes this.
```

I had to change to:

```
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.69
    hooks:
      - id: ruff
```

**Comment by fsouza** [comment]
Ohh I see, my bad, didn't realize that that was the case. In that case we should've done `--entry ruff --id lint` to keep it backwards compatible.

**Comment by charliermarsh** [comment]
I think the only way to resolve would be to delete all tags + the last ~70 commits, then re-run the process -- is that right?

**Comment by fsouza** [comment]
> I think the only way to resolve would be to delete all tags + the last ~70 commits, then re-run the process -- is that right?

You can just delete the tags and delete the `.version` file, then re-trigger the workflow. You'll have the ghost commits in the history, but they won't be tagged, so it should be fine.

**Comment by charliermarsh** [comment]
Oh ok, in that case, maybe I'll go ahead and do that. Thanks :)

**Comment by charliermarsh** [comment]
Okay great, I think that worked! Thank you. I have a better understanding of how this works now too.

I did disable `--fix` by default, can we make that a parameter in some way instead? I think it should be opt-in.

**Comment by fsouza** [comment]
> I did disable `--fix` by default, can we make that a parameter in some way instead? I think it should be opt-in.

Yeah, users can use `args` to set it in their configuration! Something like:

```yaml
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.69
    hooks:
      - id: lint
        args:
          - --fix    
```

**Pull request merged**
